trigger:
- main

variables:
- name: UBUNTU_DEP_LIST
  value: "podman pylint python3-boto3 python3-deprecation python3-flake8 python3-numpy python3-pip yajl-tools yamllint"
- name: MACOS_DEP_LIST
  value: "ghz yajl python"
- name: GHZ_URL
  value: "https://github.com/dagrayvid/ghz"

stages:
- stage: lint
  jobs:
  - job: macOS_lint
    pool:
      vmImage: "macOS-latest"
    steps:
    - script: |
        brew install ${MACOS_DEP_LIST}
      displayName: "install deps"
    - script: |
        pip install -r requirements.txt
    - script: |
        sh validate.sh || true
      displayName: "macOS linter - pip"
  - job: Linux_lint
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        sudo apt-get install -y ${UBUNTU_DEP_LIST}
      displayName: "install deps"
    - script: |
        sh validate.sh || true
      displayName: "Linux linter - Ubuntu packages"

- stage: build
  jobs:
  - job: build_ghz_linux
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        git clone ${GHZ_URL}
      displayName: 'download ghz'
    - script: |
        cd ghz/cmd/ghz
        go build .
      displayName: "build ghz"
    - publish: $(System.DefaultWorkingDirectory)/ghz/cmd/ghz/ghz
      artifact: ghz_bin

- stage: test
  dependsOn: build
  jobs:
  - job: llm_ci
    pool:
      vmImage: ubuntu-latest
    steps:
    - download: current
      artifact: ghz_bin
      displayName: "get ghz binary"
    - script: |
        sudo apt-get install -y ${UBUNTU_DEP_LIST}
      displayName: "install deps"
    - script: |
        sh scripts/start-minio.sh
      displayName: "Launch MinIO"

